package com.spacex.launches.data.models.local

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

/**
 * Represents a Flickr link entity that is stored in the local Room database.
 * This entity is used to store URLs to images from Flickr that are associated with a specific launch.
 * It is linked to the `LaunchLinksEntity` via a foreign key.
 *
 * @property id The unique ID of the Flickr link (autogenerated by Room).
 * @property launchLinksId The ID of the associated launch link, which acts as a foreign key referencing the `LaunchLinksEntity`.
 * @property small The URL of the small-sized Flickr image.
 * @property original The URL of the original-sized Flickr image.
 */
@Entity(
    tableName = "flickr-links",
    foreignKeys = [ForeignKey(
        entity = LaunchLinksEntity::class,
        parentColumns = ["id"],
        childColumns = ["launchLinksId"],
        onDelete = ForeignKey.CASCADE
    )]
)
internal data class FlickrLinkEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val launchLinksId: Long,
    val small: String,
    val original: String
)
