package com.spacex.launches.data.models.local

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

/**
 * Represents a launch fairings entity stored in the local Room database.
 * This entity contains information about the fairings (protective shells) used during a SpaceX launch.
 * It is linked to the `LaunchEntity` via a foreign key, representing the launch it is associated with.
 *
 * @property id The unique ID of the launch fairings (autogenerated by Room).
 * @property launchId The ID of the associated launch, which acts as a foreign key referencing the `LaunchEntity`.
 * @property reused Whether the fairings used in the launch were reused from a previous mission.
 * @property recoveryAttempt Whether there was an attempt to recover the fairings after the launch.
 * @property recovered Whether the fairings were successfully recovered after the launch.
 * @property ships A string representing the ships involved in the fairings recovery operation.
 */
@Entity(
    tableName = "launch-fairings",
    foreignKeys = [ForeignKey(
        entity = LaunchEntity::class,
        parentColumns = ["id"],
        childColumns = ["launchId"],
        onDelete = ForeignKey.CASCADE
    )]
)
internal data class LaunchFairingsEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val launchId: Long,
    val reused: Boolean,
    val recoveryAttempt: Boolean,
    val recovered: Boolean,
    val ships: String
)
