package com.spacex.launches.data.models.local

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

/**
 * Represents a launch failure entity stored in the local Room database.
 * This entity contains information about a failure that occurred during a SpaceX launch.
 * It is linked to the `LaunchEntity` via a foreign key, representing the launch it is associated with.
 *
 * @property id The unique ID of the launch failure (autogenerated by Room).
 * @property launchId The ID of the associated launch, which acts as a foreign key referencing the `LaunchEntity`.
 * @property time The time in seconds after launch when the failure occurred.
 * @property altitude The altitude (in meters) at which the failure occurred, if available (optional).
 * @property reason A string describing the reason for the failure.
 */
@Entity(
    tableName = "launch-failures",
    foreignKeys = [ForeignKey(
        entity = LaunchEntity::class,
        parentColumns = ["id"],
        childColumns = ["launchId"],
        onDelete = ForeignKey.CASCADE
    )]
)
internal data class LaunchFailureEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val launchId: Long,
    val time: Long,
    val altitude: Double?,
    val reason: String
)
