package com.spacex.launches.data.models.local

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

/**
 * Represents a launch links entity stored in the local Room database.
 * This entity contains various links (press kits, webcast, articles, etc.) related to a SpaceX launch.
 * It is linked to the `LaunchEntity` via a foreign key, representing the launch it is associated with.
 *
 * @property id The unique ID of the launch links (autogenerated by Room).
 * @property launchId The ID of the associated launch, which acts as a foreign key referencing the `LaunchEntity`.
 * @property presskitUrl The URL to the press kit related to the launch (optional).
 * @property webcastUrl The URL to the webcast of the launch (optional).
 * @property youtubeId The ID of the YouTube video related to the launch (optional).
 * @property articleUrl The URL to an article related to the launch (optional).
 * @property wikipediaUrl The URL to the Wikipedia page related to the launch (optional).
 */
@Entity(
    tableName = "launch-links",
    foreignKeys = [ForeignKey(
        entity = LaunchEntity::class,
        parentColumns = ["id"],
        childColumns = ["launchId"],
        onDelete = ForeignKey.CASCADE
    )]
)
internal data class LaunchLinksEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val launchId: Long,
    val presskitUrl: String?,
    val webcastUrl: String?,
    val youtubeId: String?,
    val articleUrl: String?,
    val wikipediaUrl: String?
)
