package com.spacex.launches.data.models.local

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

/**
 * Represents a Reddit link entity stored in the local Room database.
 * This entity contains various Reddit-related links (campaign, launch, media, recovery) associated with a SpaceX launch.
 * It is linked to the `LaunchLinksEntity` via a foreign key, representing the links related to the launch.
 *
 * @property id The unique ID of the Reddit link (autogenerated by Room).
 * @property launchLinksId The ID of the associated launch link, which acts as a foreign key referencing the `LaunchLinksEntity`.
 * @property campaign The URL of the Reddit campaign discussion (optional).
 * @property launch The URL of the Reddit launch discussion (optional).
 * @property media The URL of the Reddit media discussion (optional).
 * @property recovery The URL of the Reddit recovery discussion (optional).
 */
@Entity(
    tableName = "reddit-links",
    foreignKeys = [ForeignKey(
        entity = LaunchLinksEntity::class,
        parentColumns = ["id"],
        childColumns = ["launchLinksId"],
        onDelete = ForeignKey.CASCADE
    )]
)
internal data class RedditLinkEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val launchLinksId: Long,
    val campaign: String?,
    val launch: String?,
    val media: String?,
    val recovery: String?
)
