package com.spacex.launches.data.models.local

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a rocket entity stored in the local Room database.
 * This entity contains detailed information about a SpaceX rocket, such as its name, type, status, and related metadata.
 *
 * @property id The unique ID of the rocket (autogenerated by Room).
 * @property rocketId The unique identifier for the rocket.
 * @property name The name of the rocket (e.g., Falcon 9).
 * @property type The type or classification of the rocket (e.g., orbital, suborbital).
 * @property active Indicates whether the rocket is currently active.
 * @property country The country where the rocket is manufactured or launched from.
 * @property company The company responsible for building and launching the rocket (e.g., SpaceX).
 * @property wikipedia The URL to the Wikipedia page with more information about the rocket.
 * @property description A detailed description of the rocket, including its specifications and history.
 */
@Entity(tableName = "rockets")
data class RocketEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val rocketId: String,
    val name: String,
    val type: String,
    val active: Boolean,
    val country: String,
    val company: String,
    val wikipedia: String,
    val description: String
)
